image:
  file: .gitpod.Dockerfile
tasks:
  - name: init
    init: >
      go install honnef.co/go/tools/cmd/staticcheck@latest && 
      go install github.com/go-task/task/v3/cmd/task@latest &&
      go install golang.org/x/tools/cmd/goimports@latest &&
      go install github.com/mgechev/revive@latest &&
      dart --disable-analytics &&
      dart pub global activate interactive &&
      pyenv local 3.10.7 &&
      exit
ports:
  - port: 5900
    onOpen: ignore
# vnc
  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - golang.go
    - Dart-Code.dart-code
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - mathiasfrohlich.Kotlin
