image:
  file: .gitpod.Dockerfile
tasks:
  - name: install staticcheck
    init: go install honnef.co/go/tools/cmd/staticcheck@latest
  - name: install go-task
    init: go install github.com/go-task/task/v3/cmd/task@latest
  - name: install goimport
    init: go install golang.org/x/tools/cmd/goimports@latest
  - name: install revive
    init: go install github.com/mgechev/revive@latest
  - name: disable dart analytics
    init: dart --disable-analytics
  - name: install interactive (Dart REPL)
    init: dart pub global activate interactive
  - name: install springboot CLI
    init: sdk install springboot 2.7.5
ports:
  - port: 5900
    onOpen: ignore
# vnc
  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - golang.go
    - Dart-Code.dart-code
    - vscjava.vscode-java-pack
