version: "3"

tasks:
  init-go:
    cmds:
      - go mod init app
      - touch main.go
      - gp open main.go
  init-dart:
    cmds:
      - dart create -t console app
      - gp open app/bin/app.dart
  init-nu:
    cmds:
      - touch main.nu
      - gp open main.nu
  fmt-go:
    cmds:
      - goimports -w .
  fmt-dart:
    dir: app
    cmds:
      - dart format .
  vet-go:
    cmds:
      - go vet ./...
      - staticcheck ./...
  vet-dart:
    dir: app
    cmds:
      - dart analyze .
  run-go:
    cmds:
      - go mod tidy
      - go run main.go
  run-dart:
    dir: app
    cmds:
      - dart run
  run-nu:
    cmds:
      - nu main.nu
  clean-go:
    cmds:
      - rm go.* *.go
  clean-dart:
    cmds:
      - rm -rf app
  clean-nu:
    cmds:
      - rm -r *.nu
