version: "3"

tasks:
  init-go:
    cmds:
      - go mod init app
      - go get -u github.com/devlights/gomy@latest
      - touch main.go
      - gp open main.go
  init-dart:
    cmds:
      - dart create -t console app
      - gp open app/bin/app.dart
  init-java:
    cmds:
      - spring init app
      - gp open app/src/main/java/com/example/app/DemoApplication.java
  init-kotlin:
    cmds:
      - mkdir app
      - touch app/main.kt
      - gp open app/main.kt
  fmt-go:
    cmds:
      - goimports -w .
  fmt-dart:
    dir: app
    cmds:
      - dart format .
  vet-go:
    cmds:
      - go vet ./...
      - staticcheck ./...
  vet-dart:
    dir: app
    cmds:
      - dart analyze .
  lint-go:
    cmds:
      - revive -formatter stylish ./...
  run-go:
    cmds:
      - go mod tidy
      - go run main.go
  run-dart:
    dir: app
    cmds:
      - dart run
  run-java:
    dir: app
    cmds:
      - gradle bootRun
  run-kotlin:
    dir: app
    cmds:
      - kotlinc main.kt -d app.jar
      - java -jar app.jar
  clean-go:
    cmds:
      - rm go.* *.go
  clean-dart:
    cmds:
      - rm -rf app
  clean-java:
    cmds:
      - rm -rf app
  clean-kotlin:
    cmds:
      - rm -rf app
